# Generated by Django 5.0.7 on 2024-07-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_enrollment_course_alter_enrollment_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(to='myapp.instructor'),
        ),
    ]
