# Generated by Django 5.0.7 on 2024-07-21 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_course_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.instructor'),
        ),
        migrations.DeleteModel(
            name='Teaching',
        ),
    ]
