# Generated by Django 5.0.7 on 2024-07-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_end_date_schedule_updated_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='instructor_id',
            new_name='InstructorID',
        ),
    ]
