# Generated by Django 5.0.7 on 2024-07-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_instructor_id_instructor_instructorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='InstructorID',
            new_name='instructor_id',
        ),
    ]
