# Generated by Django 5.0.7 on 2024-07-22 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_instructorid_instructor_instructor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='start_date',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.schedule'),
        ),
    ]
