# Generated by Django 5.0.7 on 2024-07-22 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_start_date_schedule_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.schedule'),
        ),
    ]
