# Generated by Django 5.0.7 on 2024-07-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_wishlist_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='course',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='enrolled',
        ),
        migrations.AddField(
            model_name='course',
            name='credit_hours',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='mobile_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='myapp.course'),
        ),
    ]
