# Generated by Django 5.0.7 on 2024-07-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_course_credit_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credit_hours',
        ),
    ]
