# Generated by Django 5.0.7 on 2024-07-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_course_credit_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit_hours',
            field=models.IntegerField(default=2),
        ),
    ]
