# Generated by Django 5.0.7 on 2024-08-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='topics_covered',
            field=models.TextField(blank=True, null=True),
        ),
    ]
