# Generated by Django 5.0.7 on 2024-08-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_course_topics_covered'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'schedule'), name='unique_enrollment'),
        ),
    ]
