# Generated by Django 5.0.7 on 2024-08-10 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_enrollment_unique_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='schedule',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
    ]
