# Generated by Django 5.0.7 on 2024-08-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_rename_expertise_areas_instructor_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
